#!/bin/bash
res=$(xdpyinfo | grep dimensions)
res=${res:14:7}
if [ $res -eq 1920 ]; then
	xrandr --output eDP-1-1 --mode 3840x2160 --dpi 220
	sed -i 's#Xft.dpi:.*#Xft.dpi: 220#' ~/.Xresources
	xrdb -merge ~/.Xresources
	xrandr --dpi 220
	nitrogen --set-zoom-fill ~/.config/wall.png &
else
	xrandr --output eDP-1-1 --mode 1920x1080 --dpi 110
	sed -i 's#Xft.dpi:.*#Xft.dpi: 110#' ~/.Xresources
	xrdb -merge ~/.Xresources
	xrandr --dpi 110
	nitrogen --set-zoom-fill ~/.config/wall.png &
fi
